modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Dismount%20Entity"
logoFile="icon.png"

[[mods]]
modId="dismountentity"
version="3.0"
displayName="Dismount Entity"
displayURL="https://curseforge.com/minecraft/mc-mods/dismount-entity"
authors="Rick South"
description='''Allows players to dismount/remove/exit entities/mobs from mounted entities.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.dismountentity]]
    modId="collective"
    mandatory=true
    versionRange="[6.21,)"
    ordering="NONE"
    side="BOTH"