modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Dismount%20Entity"
logoFile="icon.png"

[[mods]]
modId="dismountentity"
version="3.2"
displayName="Dismount Entity"
displayURL="https://serilum.com/mod/dismount-entity"
authors="Rick South"
description='''Allows players to dismount/remove/exit entities/mobs from mounted entities.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jack, Jeremy Langford, Michael W. S., pepe1191, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.dismountentity]]
    modId="collective"
    mandatory=true
    versionRange="[7.55,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dismountentity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.6]"
    ordering="NONE"
    side="BOTH"
